db:
  image: postgres
  environment:
    - POSTGRES_USER=caravel
    - POSTGRES_PASSWORD=caravel
caravel:
  image: bseng/caravel
  ports:
    - 8088
  links:
    - db
  environment:
    - SECRET_KEY=MySUPERsecretKey
    - SQLALCHEMY_DATABASE_URI=postgresql://caravel:caravel@db:5432/db
