db:
  image: mariadb
  environment:
    - MYSQL_DATABASE=db
    - MYSQL_USER=caravel
    - MYSQL_PASSWORD=caravel
caravel:
  image: bseng/caravel
  ports:
    - 8088
  links:
    - db
  environment:
    - SECRET_KEY=MySUPERsecretKey
    - SQLALCHEMY_DATABASE_URI=mysql://caravel:caravel@db:3306/db
