postgres:
  image: 'postgres:latest'
  environment:
    POSTGRES_USER: caravel
    POSTGRES_PASSWORD: caravel
  container_name: postgres
caravel:
  image: bseng/caravel
  ports:
    - 8088
  links:
    - postgres
  environment:
    - SECRET_KEY=MySUPERsecretKey
    - SQLALCHEMY_DATABASE_URI=postgresql://caravel:caravel@postgres/caravel
